# Generated by Django 6.0 on 2025-12-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmmodel',
            old_name='release_year',
            new_name='relaese_year',
        ),
    ]
