# Generated by Django 6.0 on 2026-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_num',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
